language: common-lisp

env:
  matrix:
    - LISP=sbcl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Install ncurses
  - sudo apt-get install libncurses5

script:
  - cl -e '(ql:quickload :cl-charms)'
